### ISSUE TITLE
Read The Docs?

### ISSUE THREAD

**Issue by ckcollab** [CodeReclaimers/neat-python#1]
I asked on Reddit but I figured I'd make an issue so it doesn't get lost/forgotten: would you add a RTD or something explaining the API? The examples are helpful, but I think a more thorough RTD would help people get into this library.

In any case: thanks again for releasing this!

**Comment by CodeReclaimers** [comment]
Thanks for opening a reminder issue!  I'll try to get something up on RTD soon.

**Comment by CodeReclaimers** [comment]
There is now some (very minimal) documentation up on RTD: http://neat-python.readthedocs.org

I'll add to that as time goes on.

**Comment by CodeReclaimers** [comment]
Now that RTD is set up and working, I'll close this item out.  Please feel free to nag me with more issues if I'm not putting the right stuff in the docs. :)

**Comment by ckcollab** [comment]
Thanks so much, appreciate it!
