### ISSUE TITLE
Why the complicated logic with config items?

### ISSUE THREAD

**Issue by drozzy** [CodeReclaimers/neat-python#108]
I'm just curious, why the attribute classes use such (seemingly) complicated logic for defining config items:

`setattr(self, n + "_name", self.config_item_name(n))`

Instead of having a list of "config" items with a name and the same number of parameters, something like this:

`ConfigItem(name, init_mean, init_stdev, max_value, min_value, mutate_power, mutate_rate, replace_rate)`

(I'm butchering the notation here, but I think it's clear).

**Comment by drallensmith** [comment]
At least from my viewpoint, it made it considerably easier to add on additional parameters (together with those parameters having defaults) that the code doesn't assume a particular number of parameters per config item.

**Comment by d0pa** [comment]
I replaying from a phone, would like to add one more point. There multiple
configurations one is initial and second is evolved, this adds additional
complixity.

**Comment by drozzy** [comment]
Ok, it just too me a while to _get_ it, that's all.
