### ISSUE TITLE
Parallelism does not work on windows OS

### ISSUE THREAD

**Issue by cliftonarms** [CodeReclaimers/neat-python#114]
Only tested on W7 so far but parallel functions do not work on Windows platforms.

Result is either:-> evaluate does not return a result OR evaluate result delivers at same speed of single threaded script.

Works as expected on a non-windows machine.

**Comment by drallensmith** [comment]
What Python are you using (cPython, jPython, pypy, or what?) and which
parallelism? Threads or processes?

-Allen

**Comment by cliftonarms** [comment]
iPython running on jupyter notebook - tried this on 2 windows boxes (W7) and one Linux box.

The Linux machine works fine but the two windows boxes exhibit these issues

- Parallelevaluator does not run getting stuck with "****** Running generation 0 ****** "
  XOR-evolve-feedforward-parallel Backend error = "Attribute error: Cant get attribute 'eval_genome' on <module '__main__' (built-in)>

-ThreadedEvaluator just runs at single thread speed with no backend error.

These issues were found on more complex scripts before revering back to the XOR test scripts for confirmation of issues.

Python threading on windows is described as troublesome by some -
 https://docs.python.org/2/library/multiprocessing.html#windows

**Comment by bennr01** [comment]
>The Linux machine works fine but the two windows boxes exhibit these issues
>   Parallelevaluator does not run getting stuck with "****** Running generation 0 ****** "
>   XOR-evolve-feedforward-parallel Backend error = "Attribute error: Cant get attribute 'eval_genome' on <module 'main' (built-in)>

This may be a pickle issue. Have you tried using cPython or pypy instead of iPython? IIRC there was some multiprocessing+pickle bug on jupyter notebook.

> ThreadedEvaluator just runs at single thread speed with no backend error.

Due to the GIL used in most python implementations, only one thread can run at a time. This makes the `ThreadedEvaluator` slower than a single-threaded script on these implementations.

**Comment by cliftonarms** [comment]
Yes it does - My error
