### ISSUE TITLE
How to use an evolved network later on

### ISSUE THREAD

**Issue by hos** [CodeReclaimers/neat-python#115]
I am pretty new to the subject, so the question might seem silly.

How can I use the network that I evolve later on? Do I save it to a file, then load it back?

**Comment by cliftonarms** [comment]
Take a look at the code in the xor evolve-feedforward-partial.py

It saves checkpoints then reloads them

**Comment by hos** [comment]
Apparently, there is no straightforward way of doing this. According to [this issue](https://github.com/CodeReclaimers/neat-python/issues/113) one can use `pickle` to save an arbitrary Python object, so that's what I did.

    import gzip

    try:
        import cPickle as pickle # pylint: disable=import-error
    except ImportError:
        import pickle # pylint: disable=import-error

    def save_object(obj, filename):
        with gzip.open(filename, 'w', compresslevel=5) as f:
            pickle.dump(obj, f, protocol=pickle.HIGHEST_PROTOCOL)

    def load_object(filename):
        with gzip.open(filename) as f:
            obj = pickle.load(f)
            return obj

**Comment by drallensmith** [comment]
Is the slowdown from using a higher compresslevel than 5 significant? bz2
should also work, and likely would be a bit smaller, although the interface
is slightly more clunky.

-Allen

**Comment by hos** [comment]
@drallensmith I don't think it would make that much of a difference in terms of speed, at least for my code. One could make a comparison though.
