### ISSUE TITLE
Population 'initial_state' usage related

### ISSUE THREAD

**Issue by mdalvi** [CodeReclaimers/neat-python#119]
This is regarding the `initial_state` parameter of the [Population class](https://github.com/CodeReclaimers/neat-python/blob/master/neat/population.py#L23).

I can see this parameter can be useful if we want to spawn new population and species from existing, but I cannot find any example that does this. 

Do I pickle the population, species and save the generation number and then unpickle them to use it here? or is there any another way this parameter expects?

**Comment by jeteon** [comment]
The Checkpointer is an example of the use of that parameter: https://github.com/CodeReclaimers/neat-python/blob/master/neat/checkpoint.py. From looking at the code it seems that the parameter is simply a tuple of the 3 properties that you mentioned. Indeed, all the Checkpointer does is pickle these and save them to a file. When you restore it, it simply unpickles that data again.

**Comment by mdalvi** [comment]
@jeteon 
Yeah, I think I managed that like following,

```
pop = neat.Population(config=self.neat_config)
.....
.....
pop, species = pop.population, pop.species

pop_file_name = 'pop.pickle'
with open(MODEL_STORAGE_PATH + pop_file_name, 'wb') as f:
        pickle.dump(pop, f)

species_file_name = 'species.pickle'
with open(MODEL_STORAGE_PATH + species_file_name, 'wb') as f:
       pickle.dump(species, f)

......
......
......
pop, species, generations = None, None, 0
with open(MODEL_STORAGE_PATH + pop_file_name, 'rb') as f:
     pop = pickle.load(f)

with open(MODEL_STORAGE_PATH + species_file_name, 'rb') as f:
     species = pickle.load(f)

initial_state = population, species, generations 
pop = neat.Population(config=self.neat_config, initial_state=initial_state)
```
