### ISSUE TITLE
Adding new activation functions

### ISSUE THREAD

**Issue by burtontimothy** [CodeReclaimers/neat-python#12]
I'm trying to add a couple new activation functions, I thought the steps would be: 
1. Add the activation function definition in init.py (in the same format as the others)
2. Add the entry in the dictionary
3. Rebuild
4. Reinstall

However, when I added the new functions and run my script (which works with the original activation functions, even with the above modifications), I get the following error:

Traceback (most recent call last):
  File "neat_ischemia.py", line 42, in <module>
    pop = population.Population('ischemia_config')
  File "build/bdist.macosx-10.11-x86_64/egg/neat/population.py", line 30, in init
  File "build/bdist.macosx-10.11-x86_64/egg/neat/config.py", line 71, in init
AssertionError

Clearly this is being caused by the following assertion in config.py: assert all(x in self.allowed_activation for x in self.activation_functions), but I can't figure out how to update self.allowed_activation. 

How should I go about this?

**Comment by CodeReclaimers** [comment]
Right of the top of my head I can't tell what's going on, but you could print out self.activation_functions and self.allowed_activation, or maybe even ```[(x, x in self.allowed_activation) for x in self.activation_functions]``` to see what exactly is being tested in that assert.

My guess would be that either (1) you might have a typo in either the config file or in the key in ```nn/__init__.py``` or (2) Python is somehow still using a version of neat-python from before you made your modifications.

If it would be useful, I'll add myself a TODO item to make it easier to add activation functions without having to directly hack the library.  I can imagine sometimes one might want to use a particular function in a one-off manner and not have to keep around a modified version of neat-python just for that one use case.

**Comment by burtontimothy** [comment]
I actually did print out the self.allowed_activation and self.activation_functions before posting; self.allowed_activation has your original activation functions, and self.activation has my new one, so the assertion doesn't pass. It might be (2) somehow (Python still using an old version), but I saw it copy over the new version when I called "setup.py build".

It would be great if there was functionality to add activation functions without hacking the library!

**Comment by CodeReclaimers** [comment]
Yeah the way all that works right now is a bit clumsy--I'll go ahead and clean it up some, and while I'm at it I'll make it easy to just add a function to the available set.

**Comment by burtontimothy** [comment]
That sounds great, thank you!

**Comment by burtontimothy** [comment]
I figured out the problem, there's a neat/init.py and a neat/nn/init.py, which seem to be identical. I was updating neat/init.py but not neat/nn/init.py so the changes weren't having any effect.

**Comment by CodeReclaimers** [comment]
I restructured the activation function handling a bit, and now all you need to do is define your custom activation function and then make one function call to add it before creating your Config object.  I added a bit of code to demonstrate this in the "memory" example, and mention it here: http://neat-python.readthedocs.org/en/latest/customization.html#adding-new-activation-functions

Let me know if you run into any issues with it, and thanks for bringing this up in the first place!
