### ISSUE TITLE
Other people doing the (maybe exact) same thing

### ISSUE THREAD

**Issue by vladiibine** [CodeReclaimers/neat-python#14]
Hey, I found this
https://github.com/elijahr/neat-python

The API is extremely similar, the package structure resembles a lot. Do you know about this?

I was thinking that maybe you guys would like to join efforts, and create something nicer together.

Anyway, what's up with the coincidences? Do you thing you 2 would have the same inspiration sources? I mean obviously your repo is already a fork, but I'm curious about the coincidence. Did you take the same course/ watch the same presentation/ read the same book or something?

Thanks

Also, awesome library. I didn't actually know you provided a xor2_config file, so I struggled a little to make the example work, but this lib is really cool!

**Comment by vladiibine** [comment]
Got it. I saw the repo README file and it became clear.

**Comment by vladiibine** [comment]
Also, that other guy has about 100 more commits.... dunno what they do, but you might find them useful?

**Comment by CodeReclaimers** [comment]
Thanks for mentioning that other repository--I hadn't seen it before.  I'll have a look to see if there's anything useful there.

I'll also add a note to the XOR2 example on ReadTheDocs so that it's clearer that a config file is available.
