### ISSUE TITLE
UML for code

### ISSUE THREAD

**Issue by rfs13002** [CodeReclaimers/neat-python#164]
Is there a UML file for this code that I'm just not seeing or would one of you have a personal UML file that's not public? I'm interested in this project but the going is slow, learning where all the calls are going. My teacher claims a UML file should exist for this. So I thought it would be appropriate to bring it up as an "issue" despite it not being a functional problem.

**Comment by rickdgray** [comment]
@rfs13002 I realize this is pretty late but just wanted to let you know that no one uses UML. That's a very 90's thing. A couple of my teachers claimed UML was a great thing to learn and I've never once used it in the real world.

**Comment by CodeReclaimers** [comment]
@rfs13002 Sorry, I don't have any private documentation like that. 

@rickdgray UML being a "very 90's thing" is the best description I've ever heard.
