### ISSUE TITLE
Save genome and load saved genome.

### ISSUE THREAD

**Issue by gilzamir** [CodeReclaimers/neat-python#17]
Hi,

How do I save a genome and how I read a genome saved? I read the code, but I couldn't find a function to do this.

**Comment by CodeReclaimers** [comment]
You can use the pickle library from the standard library to store/load the genome object to/from a file.  There is an example of saving a genome this way in lines [66-67 of the single pole evolve script](https://github.com/CodeReclaimers/neat-python/blob/master/examples/pole_balancing/single_pole/ctrnn_evolve.py#L66), and that same genome gets loaded by the test script in [lines 12-13](https://github.com/CodeReclaimers/neat-python/blob/master/examples/pole_balancing/single_pole/ctrnn_test.py#L12).

Let me know if you run into any issues getting that to work.

**Comment by CodeReclaimers** [comment]
I'm closing this for now, please reopen if you run into any issues or need a better example.  Thanks!

**Comment by gilzamir** [comment]
Ok, thanks.

**Comment by Maskerk** [comment]
@CodeReclaimers hi，I meet the same question - Save genome and load saved genome，but I can‘t open the link https://github.com/CodeReclaimers/neat-python/blob/master/examples/pole_balancing/single_pole/ctrnn_evolve.py#L66

**Comment by byxor** [comment]
@Maskerk The folders were renamed a little bit. Here's the file you're looking for: https://github.com/CodeReclaimers/neat-python/blob/master/examples/single-pole-balancing/evolve-ctrnn.py
