### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by amirbehjat** [CodeReclaimers/neat-python#178]
Hi, 
For a paper I am comparing my method to yours. Is there any way to cite yourNEAT -Python code? Beside citing Dr. Stanely's paper.

**Comment by CodeReclaimers** [comment]
Here's a Bibtex entry example that includes the original authors of the library:
```
@misc{neat-python,
    Title = {neat-python},
    Author = {Alan McIntyre and Matt Kallada and Cesar G. Miguel and Carolina Feher da Silva},
    howpublished = {\url{https://github.com/CodeReclaimers/neat-python}}   
  }
```
