### ISSUE TITLE
question about activation function

### ISSUE THREAD

**Issue by winatawelly** [CodeReclaimers/neat-python#180]
hello, i am a bit confused about the code in activations.py, here's the sigmoid code for example.

```
def sigmoid_activation(z):
    z = max(-60.0, min(60.0, 5.0 * z))
    return 1.0 / (1.0 + math.exp(-z))
```
what i dont understand is why you need to do this `z = max(-60.0, min(60.0, 5.0 * z))` before calculating this sigmoid ? 
sorry if this is stupid question

**Comment by abrahamrhoffman** [comment]
The partial sigmoid function is created and stored in an object `z`:
```
z = max(-60.0, min(60.0, 5.0 * z))
```
then the operation is applied to perform a full sigmoid:
```
1.0 / (1.0 + math.exp(-z))
```

**Comment by winatawelly** [comment]
> The partial sigmoid function is created and stored in an object `z`:
> 
> ```
> z = max(-60.0, min(60.0, 5.0 * z))
> ```
> 
> then the operation is applied to perform a full sigmoid:
> 
> ```
> 1.0 / (1.0 + math.exp(-z))
> ```

so if i want to make derivative of sigmoid, i should just do

```
def derivatifSigmoid(y):
    return y * (1 - y)

```

right ?

**Comment by FaydSpeare** [comment]
At the point where z is -60, the sigmoid function outputs a value which is so close to 0 that it may as well be 0. Similarly where z is 60, the sigmoid function outputs a value so close to 1 that it may as well be 1. As such, the first step is just there to provide a lower- and upper-bound for z since values of z outside these bounds cause such negligible change in the output.

**Comment by winatawelly** [comment]
> At the point where z is -60, the sigmoid function outputs a value which is so close to 0 that it may as well be 0. Similarly where z is 60, the sigmoid function outputs a value so close to 1 that it may as well be 1. As such, the first step is just there to provide a lower- and upper-bound for z since values of z outside these bounds cause such negligible change in the output.
> 
> Python also probably wouldn't be too happy if you told it to calculate exp(z) for say z = 1000. Try it on a calculator ;)

finally the answer i was looking for!
thanks for the explanation, really appreciate it
