### ISSUE TITLE
What's the difference between https://github.com/neat-python/neat-python and this repo?

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [CodeReclaimers/neat-python#186]
https://github.com/neat-python/neat-python

**Comment by bennr01** [comment]
From the description of the linked repo:
>  Automatically exported from code.google.com/p/neat-python

It is a very old version. neat-python/neat-python is 609 commits behind, lacks py3 support and other features.
The `neat-python` package on pypi  refers to this repo.
TL;DR: use this repo. The other seems like an exported repository from a **very** old version.

**Comment by oushu1zhangxiangxuan1** [comment]
Thanks a lot!
