### ISSUE TITLE
How to end training early?

### ISSUE THREAD

**Issue by Jaccccc** [CodeReclaimers/neat-python#207]
I am trying to make it so that i can press a button and, using pickle, it replays the best genome of the generations, but i am not sure how to end all training immediately. I have tried using break, but that only ends one generation. Any help would be great!

**Comment by Jaccccc** [comment]
Nevermind, realised i can call the function to replay the genome and that overides the training function

**Comment by venetsia** [comment]
@penneShells can you share how you did it?
