### ISSUE TITLE
Network Architecture

### ISSUE THREAD

**Issue by kyro-dev** [CodeReclaimers/neat-python#212]
Is there any way to get the architecture (the input nodes, hidden nodes, and output nodes) of the `winner` neural network after training? I need this as array/tuple format `[number of input, number of hidden (could be array for multi-layered hidden nodes), number of output]`. I don't want to use `visualize.py` because I'm running a console application.

**Comment by BioWar** [comment]
@kyro-dev How did you solve your issue?

**Comment by kyro-dev** [comment]
No, I did not, I ended up using visualize.py. But even after that, it was difficult to understand the structure of the network.

**Comment by BioWar** [comment]
Well okay then, thanks for the quick response

**Comment by kyro-dev** [comment]
No problem.
