### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by eramosr16** [CodeReclaimers/neat-python#235]
I see 8 PR and the last activity was some years ago?.

**Comment by CodeReclaimers** [comment]
Pretty much, yeah--I just haven't been able to find time to even do maintenance.  There are a couple of forks (mentioned in the README) that seemed to be actively adding new features and keeping up with the literature, so you may want to check those out.

I should just archive the project so it's clearer that it's not likely to ever be revived.
