### ISSUE TITLE
Why Species Fitness can be lower than Best Fitness

### ISSUE THREAD

**Issue by lufthansa747** [CodeReclaimers/neat-python#24]
> Population's average fitness: -10184.15880 stdev: 28927.39939
> Best fitness: -10.10277 - size: (3, 4) - species 5 - id 2268
> Species length: 8 totaling 251 individuals
> Species ID       : [1, 2, 3, 4, 5, 6, 7, 8]
> Species size     : [11, 29, 13, 57, 40, 14, 82, 5]
> Species age      : [10, 9, 5, 2, 2, 1, 1, 0]
> Species no improv: {1: 3, 2: 1, 3: 1, 4: 1, 5: 0, 6: 0, 7: 1, 8: 0}
> Average adjusted fitness: -564.887
> Spawn amounts: [9, 25, 11, 59, 42, 15, 85, 4]
> Species fitness  : [-1834.3054339634407, -791.757092566404, -752.2287956922503, -281.3367805293633, -5.595245118281301, -72.32164843143642, -87.2591677423872, -694.2896586210072]
> Generation time: 540.122 sec
> 
>  ****** Running generation 11 ******
> 
> ..........................................................................................................................................................................................................................................................
> Population's average fitness: -5849.59915 stdev: 25451.82640
> Best fitness: -9.99070 - size: (1, 2) - species 5 - id 2790
> Species length: 8 totaling 250 individuals
> Species ID       : [1, 2, 3, 4, 5, 6, 7, 8]
> Species size     : [89, 7, 12, 31, 86, 6, 15, 4]
> Species age      : [11, 10, 6, 3, 3, 2, 2, 1]
> Species no improv: {1: 0, 2: 0, 3: 0, 4: 2, 5: 1, 6: 1, 7: 0, 8: 1}
> Average adjusted fitness: -1588.498
> Spawn amounts: [89, 7, 12, 31, 86, 6, 15, 3]
> Species fitness  : [-49.17546637257155, -868.6047802286141, -248.09082553481952, -549.7168807585341, -35.13305676350748, -1514.60139734958, -4.133573552592762, -9438.530725231149]
> Generation time: 553.786 sec

When generation 10 prints the Species fitness(which I think is the best fitness of each species), it appears that there exists an individual which performs at -5.595245118281301, however the Best fitness only changes to -9.99070 in generation 11. Why is this?

**Comment by mstechly** [comment]
Species fitness is not the best fitness of each species.
But you can check in reproduction.py, method "reproduction",  lines 25 - 45.
I was also thinking about it at some moment and found it in Stanley's original paper, however I can't find it right now.
