### ISSUE TITLE
Support Batching when evaluating genome fitness 

### ISSUE THREAD

**Issue by ephi** [CodeReclaimers/neat-python#245]
python neat supports fitness evolution by sending one example at a time. This is not very practical when one want to evaluate fitness over a big dataset.
 
So instead of just sending one example at time to the evolved network via activate(..) method. it'd be better if activate could accept a matrix N X D and output matrix N X D2 where D = the input dim (number of input neurons), D2 = the output dim (number of output neurons).

**Comment by TheMightiestCarrot** [comment]
How did you resolve this problem?

**Comment by ephi** [comment]
Not directly resolved this, I batched over HyperNEAT substrate instead. Though I'd be happy if batching were to be supported natively.
