### ISSUE TITLE
Potential memory leak, reference collection issue

### ISSUE THREAD

**Issue by sondreengebraten** [CodeReclaimers/neat-python#31]
Hi!

I am trying to use this library in a larger experimental setup but have run into some quite significant memory leaks. Debugging so far has led me to find a number of uncollectable objects like this: 

`[[[[[...], [...], None], [...], '__name__'], [...], 'species_fitness_func'], [[...], [[...], [[...], [...], 'species_fitness_func'], '__name__'], None], 'max_stagnation']`

Do you have any idea where these are found and why the python garbage collector would be unable to collect them?

To me these look like configuration objects or similar. For my setup I am pickling neural networks created with this library if that makes a difference.

In advance thanks
Sondre

**Comment by CodeReclaimers** [comment]
There are currently a lot of unnecessary references that probably form cycles.  (That's something I hope to take care of with some of the cleanup I'm doing in a branch.)  I'll take a look today and see if I can find out what's going on.

**Comment by CodeReclaimers** [comment]
What neat-python objects are you keeping references to after you're finished with a Population run?  species_fitness_func and max_stagnation only occur as member names in DefaultStagnation, and as keys in the DefaultStagnation configuration dictionary, so I'm guessing you still have a reference somewhere to a Population object.

I tried seeing what remained after a forced collection in the xor2 example on Python 3.5, and I didn't get a nested list like you have, but then I was just printing repr() or str() of the objects returned by gc.get_objects(), so I'm just kind of skimming the surface.

**Comment by CodeReclaimers** [comment]
I forgot: a Population's StatisticsReporter instance will keep accumulating data the longer the run goes on, so if you're running a large population for a long time, you will see memory increasing solely because of that, so you may need to turn off collect_statistics in your config and create your own custom stats reporter that doesn't hold references for stuff all the way back to generation 0.

**Comment by sondreengebraten** [comment]
Thank you for your reply. 

The objects I am seeing exists during a run. I ran ´gc.collect()´ during each batch of fitness evaluations using ´gc.set_debug(gc.DEBUG_SAVEALL|gc.DEBUG_UNCOLLECTABLE)´. According to the gc readme this should result in uncollectable objects being stored in ´gc.garbage´. 

I am not keeping anything post optimization, but my optimization can run for a looong time (think days or a week). I farm out evaluations to workers using Celery. In order to do so I have to pickle the genome for transfer to the worker. Serializing execution and not using a worker farm did not solve the memory leak issue so I am quite sure that this is not the problem.

Something like StatisticsReporter was exactly what I was looking for. Do you have any idea of what the memory requirement per individual is for this class?  I am not sure that neat-python is the sole cause, but would doing generation of 200 individual and 1000 generations add up to much?

**Comment by sondreengebraten** [comment]
The leaks I am seeing are quite extreme. Somehow consumptions increase by 5MBytes every second(/generation). This is with a population of 5 individuals.

**Comment by d0pa** [comment]
I am running on a single process, with initial setup, fully connected, 20 inputs, 40 hidden nodes and 3 outputs, population size 150-300 with 300 - 1000+ generation. Never had any issue with memory leaks so far memory usage is 250MB - 300MB. I am fairly sure ipython on remote machine will give me same example, will test tomorrow to be sure.
What version of neat are u using ? 
Can u reproduce same issue with XOR or other examples ?
Lastly if you run your code on local process without Celery, do you have same issue ?

**Comment by sondreengebraten** [comment]
The fault is mine and not in python-neat. I am saving a log to disk of each simulation/fitness evaluation. For some reason this counts as a reference and is keeping the python gc from collecting those objects. The memory leak does not persist if I disable logging of the fitness evaluations. 

Thank your input on this topic.

**Comment by d0pa** [comment]
I tried to reproduce your issue, here are my findings. 
Setup: Xor2 example, population 5-150, generations 4000-10000.
Config where memory does not increase:
 save_best = False
 collect_statistics = False
Config where memory increase:
 save_best = True, when False computation is faster but memory increase similarly
 collect_statistics = True, memory increases similarly

Don't think it is good idea to create so many files at such a speeds. My simulations are with 20 inputs, 3 outputs with population from 100-500 and 300 - 1000+ generation without issues (takes many hours).

**Comment by sondreengebraten** [comment]
So you actually can reproduce the issue? I was quite sure the issue was with other code I was using...

**Comment by d0pa** [comment]
Well similar increase in memory, I don't think it is a memory leak, generation_statistics and generation_cross_validation_statistics just growing with each iteration. Pickle is slow creating 1000's of files and it just overload for OS to create so many files in such a short time.

**Comment by CodeReclaimers** [comment]
I made a note to make a version of StatisticsReporter that doesn't keep everything from the beginning of time, just so you can perform super-long runs without worrying about memory for all that history.  (Maybe something to log stats into a database instead?)

@d0pa, thanks for seeing if you could reproduce it. :)

**Comment by d0pa** [comment]
@CodeReclaimers, No problem! Over weekend was able to run large simulations with dumping genome list after each generation. I can't figure out why Genome list is increasing in size, while genome size grew from 557KB to 3015KB in 2380 generations and still gowning, when population is 250 +/- 1 per each generation.
