### ISSUE TITLE
Which Python version are you using?

### ISSUE THREAD

**Issue by CodeReclaimers** [CodeReclaimers/neat-python#33]
Mainly just wondering if anybody is actually using neat-python with 2.x.  I'll keep support for 2.x in there for a while, just in case.

**Comment by d0pa** [comment]
I am using 2.x, please keep support, would be nice if I don't need to switch to 3.x :) If I can be of any help to keep support or with anything else please let me know.

**Comment by CodeReclaimers** [comment]
No problem, I'll keep 2.x support in there--it's not a huge hassle to maintain it.  I haven't kept up with 3.x adoption progress so I figured it would be good to find out if it was unnecessary. :)

**Comment by d0pa** [comment]
Thank you very much !

**Comment by sondreengebraten** [comment]
I too use 2.7

**Comment by abrahamrhoffman** [comment]
using 2.7.12 myself

**Comment by CodeReclaimers** [comment]
Thanks everybody, I'll just keep 2.x forever. :)
