### ISSUE TITLE
How do I save and load checkpoints?

### ISSUE THREAD

**Issue by BlueBlazin** [CodeReclaimers/neat-python#37]
I tried searching in the docs but couldn't find anything. I want to make a checkpoint after every generation and then be able to load it and continue training from the latest one.

Can you please provide an example of how to do it?

**Comment by CodeReclaimers** [comment]
Ah sorry about that--I temporarily removed that for the recent changes and haven't managed to put it back in yet.  I'll see if I can get that done soon and add an example that shows how to use it.

**Comment by CodeReclaimers** [comment]
I added a mechanism to do this; you can add an instance of neat.Checkpointer as a reporter, and it will write checkpoint files at specified time and/or generation intervals.

You can use neat.Checkpointer.restore_checkpoint to create a Population instance from a saved checkpoint file.

I'll try to get an example up soon, but in the meantime please feel free to try it out and let me know if you have any questions.

**Comment by CodeReclaimers** [comment]
This example how shows how to save and restore checkpoints: https://github.com/CodeReclaimers/neat-python/blob/master/examples/xor/evolve-feedforward-partial.py

I haven't really used this in a real project yet, so please let me know if you run into any issues. :)
