### ISSUE TITLE
Am I doing it right ?

### ISSUE THREAD

**Issue by d0pa** [CodeReclaimers/neat-python#39]
XOR evolve-feedforward.py in 2.7 would not run, got error: 
ValueError: invalid literal for int() with base 10: 'false' 

I changed config.py like this: https://github.com/d0pa/neat-python/commit/c5420c63e02ee9370c0e7ebf9ab3c2005d02404c

Please let me know if this is correct way contributing to a project and if fix is good :)

**Comment by CodeReclaimers** [comment]
Thanks for the patch!  I like having more explicit messages like this, so that the user doesn't have to guess at the root cause of the error.
