### ISSUE TITLE
'module' object has no attribute 'Config' + dead links in 0.9 documentation.

### ISSUE THREAD

**Issue by cafawo** [CodeReclaimers/neat-python#40]
Short comment upfront, several links in the 0.9 [documentation](https://media.readthedocs.org/pdf/neat-python/latest/neat-python.pdf) are dead ends (e.g. ''[source archive for release 0.9.](https://github.com/CodeReclaimers/neat-python/releases/tag/v0.9)'')

I installed neat-python 0.9 via pip and try to use the [xor example](https://github.com/CodeReclaimers/neat-python/tree/master/examples/xor), however, I get the following error that seems to be related to the config-feedforward.ini file but cant figure out the problem :

`Traceback (most recent call last):
  File "evolve-feedforward.py", line 72, in <module>
    run(config_path)
  File "evolve-feedforward.py", line 26, in run
    config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction,
AttributeError: 'module' object has no attribute 'Config'
`

I'm using Python 2.7.10

Many thanks for your help.

**Comment by d0pa** [comment]
when I run pip on windows no version for me of 0.9, cannot reproduce your error. Can you please download 0.9, unzip and run example from there. In case errors will try to help.

**Comment by cafawo** [comment]
I removed the pip version and installed from neat-python-master as suggested by @d0pa . Now I do not observe my initially reported error, however, it produces an error very similar to the one [previously reported](https://github.com/CodeReclaimers/neat-python/issues/39):

`
Traceback (most recent call last):
  File "evolve-feedforward.py", line 63, in <module>
    run(config_path)
  File "evolve-feedforward.py", line 28, in run
    config_file)
  File "build\bdist.win32\egg\neat\config.py", line 107, in __init__
  File "build\bdist.win32\egg\neat\genome.py", line 105, in parse_config
  File "build\bdist.win32\egg\neat\genome.py", line 45, in __init__
  File "build\bdist.win32\egg\neat\config.py", line 44, in interpret
ValueError: invalid literal for int() with base 10: **'True'**
`

**Comment by d0pa** [comment]
Apply this patch: https://github.com/d0pa/neat-python/commit/c5420c63e02ee9370c0e7ebf9ab3c2005d02404c

**Comment by cafawo** [comment]
I replaced the config.py file with yours, but the error remains. Please note that the error I get is slightly different from the one that you reported.

Your reported error:
 [`ValueError: invalid literal for int() with base 10:'false'`](https://github.com/CodeReclaimers/neat-python/issues/39)

And on my system it returns 'True'
`ValueError: invalid literal for int() with base 10: 'True'`

**Comment by d0pa** [comment]
Please double check config.py file first that patch is applied, error does not make sense :(. 
Just to make sure what example/config are you trying to run (will try to reproduce on my end).

**Comment by d0pa** [comment]
Did you delete .pyc file ? This might be a case why you getting error.

**Comment by cafawo** [comment]
I did not delete the .pyc file. I uninstalled neat-python, replaced config.py by your patch above, installed everything again and ran evolve-feedforward.py from the xor example folder. It looks like your patch solved the problem that you reported earlier on. Many thanks for that.

It appears that the algorithm is now running properly. Only at the end there appears to be a problem when visualizing:
`RuntimeError: failed to execute ['dot', '-Tsvg', '-O', 'Digraph.gv'], make sure the Graphviz executables are on your systems' path`
I checked pip freeze and found graphviz==0.5.2 on my system; hence, I don't really understand where the problem is.

Sorry for the mess, I'm fairly new to this. I'm using a windows machine - is this where the pain is coming from?

**Comment by d0pa** [comment]
It is on my todo to fix graphviz path :(, I was not able to run on windows my self. If I am not mistaken issue is with finding graphviz.exe for python or python IDE. Most likely you will have also issue with circuits example that requires pySpice.

**Comment by CodeReclaimers** [comment]
@cafawo Sorry for the confusion--you caught me updating documentation before actually making the release. :)  When you install from pip right now you're getting version 0.8, and then trying to run the 0.9 XOR example doesn't work because of all the changes from 0.8 to 0.9.  I'll see if I can get a release out on pip today just so this situation doesn't happen again.

So far I've just been testing on Linux, but I would like to make it work correctly on all the other platforms as well.  Hopefully I can find some time soon to try it out on Windows and get some instructions together for making that work.

**Comment by CodeReclaimers** [comment]
@d0pa Thanks for responding, I was very busy and then very sick for a couple of days. :)

**Comment by d0pa** [comment]
@CodeReclaimers your welcome, sorry to hear you where sick, feel better !

**Comment by CodeReclaimers** [comment]
@cafawo Version 0.9 is actually up on PyPI now, so please let me know if you're still having problems.  I'll leave this issue open until I get a chance to go check things out on Windows.

**Comment by cafawo** [comment]
@CodeReclaimers Thank you very much, so far everything is running well. Only trouble is still graphviz, but that has nothing to do with your project.

**Comment by d0pa** [comment]
@cafawo, to fix graphviz you need to do fallowing:
1. download and install graphviz from http://www.graphviz.org/Download_windows.php
2. Install python package: pip install graphviz
3. Go To: Control Panel\System and Security\System and click on "Advanced System Settings"
    On "Advanced Tab" click on "Environment Variables"
    In System Variables Find Variable "Path" and Click "Edit" 
    !! WARNING DO NOT DELETE VARIABLE VALUES !!!
    At the end of the line add ";C:\"your installation path" \Graphviz2.38\bin" (note a semicolumn)
4. Logout/Login
5. Enjoy !
