### ISSUE TITLE
Question: Adjusted fitness implementation

### ISSUE THREAD

**Issue by sondreengebraten** [CodeReclaimers/neat-python#43]
Hi! 

The original NEAT paper adjusts fitness based on the distance to all other individuals in the population. In neat-python I found this snippet of relevance:

```
# Compute adjusted fitness.
species_sum = 0.0
for m in itervalues(s.members):
    af = m.fitness / len(s.members)
    species_sum += af

sfitness = species_sum / len(s.members)
species_fitness.append((sid, s, sfitness))
avg_adjusted_fitness += sfitness
```

It appears as if fitness is adjusted here by the size of the species squared not the actual distance to all other member of the population. Is this correct?

Best
Sondre

**Comment by d0pa** [comment]
I am interested too, specifically this line: af = m.fitness / len(s.members). Looking at Multineat implementation source code (assuming I am looking at right place) :), looks like multi neat calculates just mean. Multineat code: https://github.com/peter-ch/MultiNEAT/blob/master/src/Population.cpp

**Comment by CodeReclaimers** [comment]
You're right @sondreengebraten, that's probably a copy/paste/edit mistake.   I just pushed a fix for that.

**Comment by CodeReclaimers** [comment]
Please feel free to reopen if the fix doesn't fully address the discrepancy with the paper.  Thanks for finding that!
