### ISSUE TITLE
reset_on_extinction   = True, insufficient arguments

### ISSUE THREAD

**Issue by cafawo** [CodeReclaimers/neat-python#44]
First let me thank you for some great code and the previous help.

With config:
[NEAT]
...
reset_on_extinction   = True

I run into the following error when all species are extinct:

`
All species extinct.
Traceback (most recent call last):
 ...
  File "build\bdist.win32\egg\neat\population.py", line 88, in run
TypeError: create_new() takes exactly 4 arguments (2 given)
`

Unfortunately I could not find out which 2 arguments are missing.

In addition, is there a simple way to track how often the program ran into extinction?

Many thanks for your help.

**Comment by CodeReclaimers** [comment]
Glad to help!  Thanks for reporting the bug, I usually let it throw the exception on complete extinctions, as it usually means my current experiment is probably not set up correctly, so I hadn't noticed it. :)
