### ISSUE TITLE
initial_connection fs_neat and partial issues

### ISSUE THREAD

**Issue by stark7** [CodeReclaimers/neat-python#45]
initial_connection      = fs_neat
is breaking at:
g.connect_fs_neat() it should be g.connect_fs_neat(config)
and even so there's other errors associated with selecting fs_neat

There's also an issue when parsing the initial_connection      = partial at line 59 in genome.py

**Comment by d0pa** [comment]
@stark7, please take a look at this patch https://github.com/d0pa/neat-python/commit/0265a72db195ecb76e4b46f8851298c19800e5e0 this should solve issue fs_neat, will look later at partial connection. Please note I did not tested that fs_neat creates correct connections.

**Comment by d0pa** [comment]
Please see example of XOR config with 50% partially connected network.
https://github.com/CodeReclaimers/neat-python/compare/master...d0pa:patch-4

**Comment by stark7** [comment]
Thanks d0pa - you also need to add config to

genome.py
line 362: 

g.connect_fs_neat(config)

**Comment by CodeReclaimers** [comment]
Thanks for reporting these problems @stark7!  And thanks @d0pa for the patches!  I just committed all these changes.  I think I'll also add tests for those options as well.
