### ISSUE TITLE
stop on population's average fitness threshold instead of an individuals'

### ISSUE THREAD

**Issue by stark7** [CodeReclaimers/neat-python#48]
I found that an individual coming from a very strong population with a high average fitness was actually much better at predicting output in brand new situations than an individual who just solved the problem earlier on - so I'm proposing a config threshold that will let an algorithm run until the entire population reaches a minimum or maximum threshold before picking an individual with the best fitness.

Right now the best way I can accomplish that is to set a max fitness threshold above something that I know can be calculated and then hope to avoid mass extinctions along the way.

**Comment by CodeReclaimers** [comment]
That sounds like a good thing to have, I'll get that in there shortly.  I'm also playing with a "species elitism" mechanism that will prevent the removal of the last N species, which should address the mass extinction problem.

**Comment by CodeReclaimers** [comment]
I just pushed a change in feafb59551f5ecc1789f439dc1e12a8a49efbfd0 that replaces the NEAT max_fitness_threshold option into a fitness_criterion selection (min, max or mean) and fitness_threshold.
