### ISSUE TITLE
genes.py: ValueError: Invalid conversion specification

### ISSUE THREAD

**Issue by mstechly** [CodeReclaimers/neat-python#5]
I've got the same error as the last time from genes.py, line 91.
Current code is:

    return "Node {0:2d} {1:6!s}, bias {2:2.10!s}, response {3:2.10!s}, activation {4!s}, time constant {5:2.5!s}".format(self.ID, self.type, self.bias, self.response, self.activation_type, self.time_constant)

while it should be:

    return "Node {0:2d} {1!s:6}, bias {2!s:2.10}, response {3!s:2.10}, ...

or:

    return "Node {0:2d} {1:6}, bias {2:2.10}, response {3:2.10}, ...

The same problem (and probably fix) should appear in genes.py, line 21.

I looked for other such cases using "grep -nr '!s'  neat/" and found nothing, so I hope this is the last case.

**Comment by CodeReclaimers** [comment]
Thanks!

**Comment by CodeReclaimers** [comment]
This is fixed in 5a6d7e1aa403ddc1f280f0cb6e567414a1e251f7.
