### ISSUE TITLE
double pole: import nn_pure

### ISSUE THREAD

**Issue by mstechly** [CodeReclaimers/neat-python#6]
After running evolve_double_pole.py I got:

```
(...)/double_pole/cart_pole.py", line 5, in <module> from neat.nn import nn_pure as nn
ImportError: cannot import name nn_pure
```

phrase "nn_pure" occurs only in double pole example.

**Comment by CodeReclaimers** [comment]
Yeah the double pole example is just generally broken at the moment. :)  After I get some current bug fixes and improvements wrapped up I'll see if I can get it working again.

**Comment by CodeReclaimers** [comment]
I'll probably not be adding the double-pole example as it originally was, just because it doesn't add much beyond the single-pole example as an example of usage.  I will probably try to include an example that incorporates an external physics engine, though.
