### ISSUE TITLE
Question: Bound value of output nodes

### ISSUE THREAD

**Issue by TranTrongTin** [CodeReclaimers/neat-python#66]
I'm just a new user to NEAT-Python and have looked at the Xor example. Now I want to use Neat on a specific dataset and its class is either 2 or 4. However, as far as I can see is that the output value using FeedForward NN is ranged only from 0 to 1 and (seemly) there is no configuration for that.
Thus is there anyway to config? Or I have to modify class output of the dataset?

Thanks in advance.

**Comment by d0pa** [comment]
You want to modify output to value between 2 to 4 instead of value between 0 to 1 ?

**Comment by uberscientist** [comment]
if it's EITHER 2 or 4, you can modify your training data to be 1 or 0 with something like:
`data.y = [ 0 if y < 4 else 1 for y in data.y ]`

It would be useful if you skim the **Preprocessing** docs in sci-kit learn to get an idea about how to manipulate your training data to work with various ML models, including NEAT: http://scikit-learn.org/stable/modules/preprocessing.html#preprocessing

**Comment by TranTrongTin** [comment]
@uberscientist Thanks for your suggestion :D

**Comment by unnir** [comment]
sorry for posting it here, but it's kind of related to the topic. 

I want to try the NEAT for my issue,  I have an input, f.i.:

`a=[[0,1],[0,1],[0,-1],[0,-1]]`

And for the output I want to get:
`a=[[0,1],[1,0],[-1,0],[0,-1]]`

As you may probably guess, the idea is to sort elements inside the lists in order to get the zero sum of these list.
`[0,1] + [1,0] + [-1,0] + [0,-1] = [0,0]`

Currently, in my code, I'm checking it using the function _zeroOffset_.

So, my question is it possible to use a function for the output?

**Comment by d0pa** [comment]
@unnir, are you trying to train neat so that for input=[[0,1],[0,1],[0,-1],[0,-1]], neat output will be [[0,1],[1,0],[-1,0],[0,-1]] ?

**Comment by unnir** [comment]
Yes, but it is simplification of my issue, basically I'm want to sort the
elements in the list.


I just want to know what is feasible with NEAT.

-- 
Vadim Borisov
Sent with Airmail

**Comment by d0pa** [comment]
I don't see an reason why not, you can use xor example, change num_outputs to 2 in config and modify fitness calculation so that you calculate error utilizing 2 inputs and 2 outputs.

**Comment by unnir** [comment]
@d0pa I guess I have not explain my issue correctly. Sorry, it is my big problem.

So, I have an input:

`in=[[0,1],[0,1],[0,-1],[0,-1]]`


But I have no idea which output is correct one for my input list in (if I knew it I would not disturb you here), util I applied a special evaluation function for the output. And it returns True of False.

Example:

```
out=[[0,1],[1,0],[-1,0],[0,-1]]
if Evaluation(out) == True:
             return(out)
```

**Comment by d0pa** [comment]
No need to be sorry at all.
Just to be clear, your input for genome is element wise form in=[[0,1],[0,1],[0,-1],[0,-1]] list (it is same as in xor example except you have 2 outputs) - correct ?

If yes, easiest way would be to prepare your input/output training data, where for each input in training data, you have defined expected output and then compare your expected output with actual neat output for each element in input list and calculate score (sum all scores from each input/output).

If no, provide more detailed example of your problem.

**Comment by unnir** [comment]
@d0pa I think I got it. Thank you very much!
 
For the following questions (hope there will be nothing to ask), I would use a new issue block:)
