### ISSUE TITLE
How to run generations until fitness_threshold is reached

### ISSUE THREAD

**Issue by vishiswoz** [CodeReclaimers/neat-python#69]
If we want to keep running generations until a certain fitness threshold is reached, how would we go about that. I know that the code will stop executing automatically, but you have to still specify a maximum amount of generation, can't it just be infinite until the threshold is reached (because we know it will eventually)

**Comment by CodeReclaimers** [comment]
For now you can just give it a very large number of generations, such as 2**64.  That would take about half a billion years to run if each generation takes one millisecond. :)

For the future, I will probably make the "number of generations" argument to `Population.run` optional.  Once that change is made, you can just omit the number of generations and it will just run until a solution is found or extinction occurs.
