### ISSUE TITLE
genome.py: AttributeError: 'NodeGene' object has no attribute 'id'

### ISSUE THREAD

**Issue by mstechly** [CodeReclaimers/neat-python#7]
I created a network with config parameter hidden_nodes=50.
I got following error in genome.py in class FFGenome, method add_hidden_nodes:

    AttributeError: 'NodeGene' object has no attribute 'id'.

I had to change all ".id" to ".ID" in this function, so pre.id -> pre.ID, post.id -> post.ID, node_gene.id -> node_gene.ID and it seems to be working.
I changed it only in the FFGenome, but add_hidden_nodes in Genome will probably produce the same error.

**Comment by CodeReclaimers** [comment]
This is fixed in 5a6d7e1aa403ddc1f280f0cb6e567414a1e251f7.  Thanks for reporting it!
