### ISSUE TITLE
Why is the sigmoid activation function input being weighed by "5"?

### ISSUE THREAD

**Issue by adrianjrandall** [CodeReclaimers/neat-python#81]
Not an issue, but just a quick question for why the sigmoid activation function is coded this way. Looking through the [activations.py](https://github.com/CodeReclaimers/neat-python/blob/master/neat/activations.py) file, I see `z` is being multiplied by 5. Can someone clarify why that's being done? Thanks so much. 

    def sigmoid_activation(z):
        z = max(-60.0, min(60.0, 5.0 * z))
        return 1.0 / (1.0 + math.exp(-z))`

**Comment by CodeReclaimers** [comment]
The basic idea was to make most of the built-in activation functions have most of their "interesting" behavior occur [in the same region](http://neat-python.readthedocs.io/en/latest/activation.html).  That way if you are evolving a network that has multiple different possible activation functions, a mutation which changes the activation function won't require a drastic change in the inputs to be in a region where the activation function isn't saturated.

If you need to use the standard sigmoid function, you can always [add your own without a huge amount of trouble](http://neat-python.readthedocs.io/en/latest/customization.html#new-activation-functions).

**Comment by CodeReclaimers** [comment]
I'm closing this, but if you have any more questions please feel free to re-open or start a new issue.  Thanks!
