### ISSUE TITLE
Question: performance compared to C++/Java libraries?

### ISSUE THREAD

**Issue by fearofcode** [CodeReclaimers/neat-python#82]
This library looks dope, thanks for putting it together.

Just wondering what performance is like compared to some of the other libraries out there?

I realize that is a vague question and you can only compare specific library versions to one another so without stating a lot more information, etc., it's a very vague question.

All I'm really wondering is: I want to use NEAT to solve the standard single-pole balancing task.

I have an 8 core i7 machine with 16 GB of RAM to work with.

Is this library fast enough to get the job done? Would it probably run a lot faster if I used Kenneth Stanley's C++ code?

My experience with evolutionary algorithms is that the bottleneck is objective function evaluation, in this case a physics simulation.

If I'm using a Python physics engine which merely consists of Python bindings to a C physics engine, it should give a performance profile similar to just writing all the code in C, right?

Thanks!

**Comment by d0pa** [comment]
You can try signle-pole balancing from neat-python library, see  examples folder. I am using mostly neat-python myself, so far did not hit any bottle necks where I would consider switching to another neat implementations.

**Comment by fearofcode** [comment]
Sure enough, I ran it and it runs in a reasonable amount of time. Thanks!

I changed the fitness function to encourage it to converge in position. What's on master allows for controllers that just oscillate back and forth. The original NEAT paper has a different objective function meant to deal with this. After switching to that, it converges to the origin and doesn't drift over time.

Hooray!
