### ISSUE TITLE
What type of Neural Network is generated?

### ISSUE THREAD

**Issue by cassioalmeidas** [CodeReclaimers/neat-python#85]
MLP? Kohonen?

**Comment by CodeReclaimers** [comment]
There are three basic network types included: 

- nn, which can either be a classic feed-forward network or a discrete-time recurrent network.
- ctrnn, continuous-time recurrent network
- iznn, a recurrent network with spiking neurons using the Izhikevich model

A little bit of effort has gone into making it easier to implement your own network types for use in the library, so if you have a need for a particular network type it might be possible to make it work.

**Comment by CodeReclaimers** [comment]
Please feel free to reopen this issue or creating a new one if you have any further questions.
