### ISSUE TITLE
difference between this version and the PEAS version minus hyper-neat?

### ISSUE THREAD

**Issue by garnier77** [CodeReclaimers/neat-python#86]
Hello everyone I'm fairly new in learning AI and python. I stumbled on another python implementation of NEAT and wanted to know if the core of the NEAT program is the same or since this repository is updated more frequently that this version is more stable. Thank you for any info

**Comment by CodeReclaimers** [comment]
This implementation was forked from https://github.com/neat-python/neat-python, and I'm not sure if the original authors of that started from scratch or borrowed from some other source.

As far as stability goes, this implementation will probably still change a bit before version 1.0, but after that I may just stick to bug fixes, depending on how much free time I have. :) So I suppose using this one would have the benefit that a few other people will occasionally find and fix some bugs, whereas the PEAS implementation (unfortunately) seems to not be updated any more.

**Comment by garnier77** [comment]
I see thank you for answering the question. Very eager to see how this NEAT implementation "evolves" (no pun intended lol)  and possibly a hyper-neat implementation down the road. After reading Stanley's paper it appears that NEAT can find solutions that are not intuitive to humans but actually work in real life which is fascinating to me. Keep up the great work!!!

**Comment by CodeReclaimers** [comment]
Thanks! Please feel free to reopen this issue or create a new one if you have any further questions or issues.
