### ISSUE TITLE
mutate_value in FloatAttribute: Result is not clamped when mutated (as opposed to replaced)

### ISSUE THREAD

**Issue by drallensmith** [CodeReclaimers/neat-python#90]
Hi. In 0.91's attributes.py, mutate_value in FloatAttribute has the following code:

```python
        if r < replace_rate + mutate_rate:
            mutate_power = getattr(config, self.mutate_power_name)
            return value + gauss(0.0, mutate_power)
```
This return does not clamp the result; the clamping is done (within init_value) if replacing, and if unchanged the final returned result is clamped:
```python
        return self.clamp(value, config)
```
But if the result is mutated (not replaced), it isn't clamped.

-Allen

**Comment by drallensmith** [comment]
I have done the change on a fork and submitted a pull request (#91).

-Allen

**Comment by CodeReclaimers** [comment]
Hi Allen, thanks for all the work you put into this!
